import { Inter } from 'next/font/google'

import Header from './_components/common/Header'
import './styles/css/bootstrap.css'
import './styles/css/style.css'
import Footer from './_components/common/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        
        {children}<Footer></Footer></body>
    </html>
  )
}
